"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
type FeedItem={title:string;detail:string;time:string;kind:"weather"|"earthquake"};
type HazardResponse={generatedAt:string;currentWeather:{temperature:number;apparent:number;humidity:number;wind:number;condition:string;icon:string};weather:{count:number;highest:string;headline:string};earthquakes:{count:number;strongestMagnitude:number|null;headline:string};updates:FeedItem[];sources:{nws:string;usgs:string;weather:string}};
const fallback:HazardResponse={generatedAt:"",currentWeather:{temperature:0,apparent:0,humidity:0,wind:0,condition:"Loading",icon:"◌"},weather:{count:0,highest:"Unavailable",headline:"Weather feed is temporarily unavailable"},earthquakes:{count:0,strongestMagnitude:null,headline:"Earthquake feed is temporarily unavailable"},updates:[],sources:{nws:"https://api.weather.gov",usgs:"https://earthquake.usgs.gov",weather:"https://open-meteo.com/"}};
function relativeTime(value:string){const m=Math.max(0,Math.round((Date.now()-new Date(value).getTime())/60000));return m<1?"Just now":m<60?`${m} min ago`:`${Math.floor(m/60)} hr ago`}
export default function Home(){
 const[data,setData]=useState(fallback),[state,setState]=useState<"loading"|"live"|"error">("loading");
 const currentDate=useMemo(()=>new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric"}).format(new Date()),[]);
 const loadData=useCallback(async()=>{setState("loading");try{const r=await fetch("/api/hazards",{cache:"no-store"});if(!r.ok)throw new Error();setData(await r.json());setState("live")}catch{setState("error")}},[]);useEffect(()=>{void loadData()},[loadData]);
 const elevated=data.weather.count>0;const hazards=[{name:"Weather alerts",level:data.weather.count?data.weather.highest:"Normal",note:data.weather.headline,icon:"ϟ",live:true,href:data.sources.nws,source:"NWS"},{name:"Earthquakes",level:data.earthquakes.count?`${data.earthquakes.count} today`:"Normal",note:data.earthquakes.headline,icon:"⌁",live:true,href:data.sources.usgs,source:"USGS"},{name:"Flood sensors",level:"Planned",note:"Local sensor connection is next",icon:"≈",live:false,href:"https://waterdata.usgs.gov/nwis",source:"USGS Water"},{name:"Wildfire",level:"Planned",note:"NASA FIRMS integration is next",icon:"△",live:false,href:"https://firms.modaps.eosdis.nasa.gov/",source:"NASA FIRMS"}];
 return <main>
  <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">S</span><span>Sentinel</span></a><nav aria-label="Primary navigation"><a className="active" href="#overview">Overview</a><a href="#hazards">Hazards</a><a href="#updates">Updates</a><a href="#about">About</a></nav><div className="header-tools"><a className="local-weather" href={data.sources.weather} target="_blank" rel="noreferrer"><span>{data.currentWeather.icon}</span><div><strong>{state==="live"?`${data.currentWeather.temperature}°F`:"--°F"}</strong><small>{data.currentWeather.condition} · Lake Forest</small></div></a><span className={`status-dot ${state}`}><i/>{state==="live"?"Live":"Updating"}</span></div></header>
  <section className="hero" id="top"><div><p className="eyebrow">Community risk monitor</p><h1>Know what&apos;s happening.<br/>Know what to do.</h1><p className="lede">Sentinel brings official hazard feeds and local sensor readings into one clear, practical view.</p></div><div className="location-form"><label>Monitoring area</label><div><input value="Lake Forest, Illinois" readOnly aria-label="Monitoring area"/><button onClick={()=>void loadData()} disabled={state==="loading"}>{state==="loading"?"Updating…":"Refresh"}</button></div></div><a className="photo-credit" href="https://unsplash.com/photos/dramatic-storm-clouds-gather-over-a-vast-landscape-sFkEeMLrlnM" target="_blank" rel="noreferrer">Background: Shane Gallagher / Unsplash ↗</a></section>
  <section className="dashboard" id="overview"><div className="area-heading"><div><p className="eyebrow">Current area</p><h2>Lake Forest, IL</h2></div><p>{currentDate}<br/><span>{data.generatedAt?`Feed checked ${relativeTime(data.generatedAt)}`:"Waiting for official feeds"}</span></p></div>
   {state==="error"&&<div className="feed-notice" role="alert">Official feeds could not be reached. Try refreshing in a moment. No cached information is being presented as current.</div>}
   <div className="summary-grid"><article className="overall-card"><div className={`risk-gauge ${elevated?"":"normal"}`}><strong>{elevated?"AWARE":"NORMAL"}</strong><span>{elevated?`${data.weather.count} active alerts`:"No active IL alerts"}</span></div><div><p className="eyebrow">Overall status</p><h3>{elevated?"Review active advisories":"No active Illinois alerts"}</h3><p>{elevated?data.weather.headline:"The National Weather Service currently reports no active alerts for Illinois. Conditions can change quickly."}</p><a href="#hazards">Review hazard details →</a></div></article><article className="conditions-card"><p className="eyebrow">Official feed summary</p><div className="temperature">{data.weather.count}<span> alerts</span></div><p>National Weather Service · Illinois</p><dl><div><dt>USGS events</dt><dd>{data.earthquakes.count}</dd></div><div><dt>Strongest</dt><dd>{data.earthquakes.strongestMagnitude??"—"}</dd></div><div><dt>Window</dt><dd>Past 24 hr</dd></div></dl></article></div>
   <div className="section-title" id="hazards"><div><p className="eyebrow">Hazard overview</p><h2>What we&apos;re watching</h2></div><span>{state==="live"?"Live data":"Checking data"}</span></div><div className="hazard-grid">{hazards.map(h=><a className="hazard-card" href={h.href} target="_blank" rel="noreferrer" key={h.name} aria-label={`Open ${h.source} source for ${h.name}`}><span className="hazard-icon">{h.icon}</span><div><h3>{h.name}{h.live&&<small> LIVE</small>}</h3><p>{h.note}</p><b className="card-source">View {h.source} source ↗</b></div><span className={`level ${h.live&&h.level!=="Normal"?"watch":""}`}>{h.level}</span></a>)}</div>
   <section className="updates" id="updates"><div className="section-title"><div><p className="eyebrow">Official activity</p><h2>Recent updates</h2></div></div><div className="update-list">{data.updates.length?data.updates.map((u,i)=><a href={u.kind==="weather"?data.sources.nws:data.sources.usgs} target="_blank" rel="noreferrer" key={`${u.title}-${i}`}><time>{relativeTime(u.time)}</time><span className={`update-marker ${u.kind}`}/><div><h3>{u.title} <small>↗</small></h3><p>{u.detail}</p></div></a>):<p className="empty-state">{state==="loading"?"Contacting official feeds…":"No recent feed items are available."}</p>}</div></section>
   <div className="source-panel weather-sources"><div><span>Verified public sources</span><strong>Explore the original data</strong></div><a href={data.sources.weather} target="_blank" rel="noreferrer">Open-Meteo Weather <b>↗</b></a><a href={data.sources.nws} target="_blank" rel="noreferrer">National Weather Service <b>↗</b></a><a href={data.sources.usgs} target="_blank" rel="noreferrer">USGS Earthquakes <b>↗</b></a></div><p className="source-note">Weather data: Open-Meteo (CC BY 4.0). Background photograph: Shane Gallagher on Unsplash. Sentinel summarizes public feeds and does not issue emergency alerts.</p>
  </section><footer id="about"><div><strong>Sentinel</strong><p>An open-source disaster awareness project.</p></div><p>Informational service — always follow official emergency guidance.</p></footer>
 </main>
}
