"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
type FeedItem={title:string;detail:string;time:string;kind:"weather"|"earthquake"};
type Suggestion={label:string;latitude:number;longitude:number};
type Intelligence={water:{available:boolean;nearbyCount:number;closest:null|{id:string;name:string;distanceMiles:number;stage:number|null;stageUnit:string|null;streamflow:number|null;streamflowUnit:string|null;category:string;forecastStage:number|null;forecastCategory:string;impact:string|null;url:string};gauges:Array<{id:string;name:string;distanceMiles:number;category:string;stage:number|null;unit:string|null;url:string}>;sourceUrl:string};fema:{available:boolean;count:number;declarations:Array<{disasterNumber:number;state:string;incidentType:string;declarationTitle:string;url:string}>};hurricanes:{available:boolean;count:number;storms:Array<{name:string;classification:string;windMph:number;url:string}>};connectors:{airnow:{configured:boolean};firms:{configured:boolean}};specialized:Array<{name:string;agency:string;url:string}>};
type Data={generatedAt:string;scope:"national"|"local";query:string;location:string;geocoded:boolean;coordinates:{latitude:number;longitude:number}|null;availability:{nws:boolean;usgs:boolean;weather:boolean};currentWeather:{available:boolean;temperature:number|null;apparent:number|null;humidity:number|null;wind:number|null;condition:string;icon:string;sourceName:string;sourceUrl:string};weather:{count:number;highest:string;headline:string};earthquakes:{count:number;strongestMagnitude:number|null;headline:string};updates:FeedItem[];sources:{nws:string;usgs:string;weather:string}};
const fallback:Data={generatedAt:"",scope:"national",query:"",location:"United States",geocoded:false,coordinates:null,availability:{nws:false,usgs:false,weather:true},currentWeather:{available:true,temperature:null,apparent:null,humidity:null,wind:null,condition:"Nationwide overview",icon:"◎",sourceName:"National Weather Service",sourceUrl:"https://www.weather.gov/"},weather:{count:0,highest:"Loading",headline:"Loading nationwide alerts"},earthquakes:{count:0,strongestMagnitude:null,headline:"Loading earthquake activity"},updates:[],sources:{nws:"https://www.weather.gov/",usgs:"https://earthquake.usgs.gov/",weather:"https://open-meteo.com/"}};
const backgrounds=[
 {url:"/backgrounds/sentinel-storm.webp",credit:"Sentinel original · AI-assisted",page:"https://github.com/3shmakerw4r/sentinel-disaster-alert"},
 {url:"/backgrounds/sentinel-wildfire.webp",credit:"Sentinel original · AI-assisted",page:"https://github.com/3shmakerw4r/sentinel-disaster-alert"},
 {url:"/backgrounds/sentinel-flood.webp",credit:"Sentinel original · AI-assisted",page:"https://github.com/3shmakerw4r/sentinel-disaster-alert"}
];
function relative(value:string){const minutes=Math.max(0,Math.round((Date.now()-new Date(value).getTime())/60000));return minutes<1?"Just now":minutes<60?`${minutes} min ago`:`${Math.floor(minutes/60)} hr ago`}

function MiniLocationMap({latitude,longitude,label}:{latitude:number;longitude:number;label:string}){
 const west=longitude-.12,east=longitude+.12,south=latitude-.075,north=latitude+.075,src=`https://www.openstreetmap.org/export/embed.html?bbox=${west}%2C${south}%2C${east}%2C${north}&layer=mapnik&marker=${latitude}%2C${longitude}`;
 return <article className="mini-map-card"><iframe className="mini-map-canvas" src={src} title={`Interactive map of ${label}`} loading="lazy"/><div className="mini-map-label"><div><span>Selected location</span><strong>⌖ {label}</strong></div><a href={`/map?q=${encodeURIComponent(label)}`}>Explore full map →</a></div></article>
}

export default function Home(){
 const[data,setData]=useState(fallback),[intel,setIntel]=useState<Intelligence|null>(null),[state,setState]=useState<"loading"|"live"|"error">("loading"),[query,setQuery]=useState(""),[background,setBackground]=useState(0),[searchError,setSearchError]=useState(""),[suggestions,setSuggestions]=useState<Suggestion[]>([]);
 const date=useMemo(()=>new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric"}).format(new Date()),[]);
 const load=useCallback(async(value="")=>{setState("loading");setSearchError("");try{const response=await fetch(`/api/hazards${value?`?q=${encodeURIComponent(value)}`:""}`,{cache:"no-store"});if(!response.ok)throw new Error();const next=await response.json() as Data;if(value&&!next.geocoded){setSearchError("Location not found. Try a city and state or a five-digit ZIP code.");setState("live");return}setData(next);const point=next.coordinates?`?lat=${next.coordinates.latitude}&lon=${next.coordinates.longitude}`:"";fetch(`/api/intelligence${point}`,{cache:"no-store"}).then(r=>r.ok?r.json():null).then(result=>setIntel(result)).catch(()=>setIntel(null));setState("live")}catch{setState("error")}},[]);
 useEffect(()=>{const initial=new URLSearchParams(window.location.search).get("q")?.trim()??"";if(initial){setQuery(initial);void load(initial)}else void load()},[load]);useEffect(()=>{const timer=setInterval(()=>setBackground(value=>(value+1)%backgrounds.length),12000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(query.trim().length<2){setSuggestions([]);return}const controller=new AbortController(),timer=setTimeout(async()=>{try{const response=await fetch(`/api/suggest?q=${encodeURIComponent(query)}`,{signal:controller.signal});const result=await response.json() as {suggestions:Suggestion[]};setSuggestions(result.suggestions)}catch{}},250);return()=>{clearTimeout(timer);controller.abort()}},[query]);
 function search(event:FormEvent){event.preventDefault();setSuggestions([]);if(query.trim())void load(query.trim())}
 function pick(place:Suggestion){setQuery(place.label);setSuggestions([]);void load(place.label)}
 const image=backgrounds[background],feedCount=Object.values(data.availability).filter(Boolean).length,partial=state==="live"&&feedCount<3,elevated=data.weather.count>0,isLocal=data.scope==="local";
 const water=intel?.water.closest,hazards=[{name:isLocal?"Local weather alerts":"U.S. weather alerts",level:data.weather.count?data.weather.highest:data.availability.nws?"Normal":"Offline",note:data.weather.headline,icon:"ϟ",live:data.availability.nws,href:data.sources.nws,source:"NWS"},{name:isLocal?"Nearby earthquakes":"Earthquakes",level:data.earthquakes.count?`${data.earthquakes.count} today`:data.availability.usgs?"Normal":"Offline",note:data.earthquakes.headline,icon:"⌁",live:data.availability.usgs,href:data.sources.usgs,source:"USGS"},{name:"Flood monitoring",level:water?.category??(isLocal?"Checking":"Search area"),note:water?`${water.name}: ${water.stage??"—"} ${water.stageUnit??""} · ${water.streamflow??"—"} ${water.streamflowUnit??""}`:"Search a location for live river conditions",icon:"≈",live:Boolean(water),href:water?.url??"https://water.noaa.gov/",source:"NOAA NWPS"},{name:"Wildfire activity",level:intel?.connectors.firms.configured?"Connected":"Key needed",note:intel?.connectors.firms.configured?"NASA satellite fire connector is active":"FIRMS is ready for a protected MAP key",icon:"△",live:Boolean(intel?.connectors.firms.configured),href:"https://firms.modaps.eosdis.nasa.gov/",source:"NASA FIRMS"}];
 return <main>
  <header className="topbar"><a className="brand" href="#top"><img src="/sentinel-logo.webp" alt=""/><span>Sentinel</span></a><nav aria-label="Primary navigation"><a className="active" href="#overview">Overview</a><a href="#hazards">Hazards</a><a href="#updates">Updates</a><a href="#sources">Sources</a><a href="/map">Map</a></nav><div className="header-tools"><a className="local-weather" href={data.currentWeather.sourceUrl} target="_blank" rel="noreferrer"><span>{data.currentWeather.icon}</span><div><strong>{isLocal&&data.currentWeather.temperature!==null?`${data.currentWeather.temperature}°F`:"USA"}</strong><small>{isLocal?`${data.currentWeather.condition} · ${data.location}`:"Nationwide alert overview"}</small></div></a><span className={`status-dot ${partial?"loading":state}`}><i/>{partial?`${feedCount}/3 feeds`:state==="live"?"Live":"Updating"}</span></div></header>
  <section className="hero nationwide-hero" id="top" style={{backgroundImage:`linear-gradient(105deg,rgba(5,40,30,.93),rgba(13,67,48,.62)),url(${image.url})`}}><div><p className="eyebrow">United States hazard monitor</p><h1>{isLocal?data.location:<>Know what&apos;s happening.<br/>Know what to do.</>}</h1><p className="lede">{isLocal?"Localized alerts, weather, and nearby earthquake activity from official public sources.":"Active alerts across the United States, with local details available by city, state, or ZIP code."}</p></div><form className="location-form search-form" onSubmit={search}><label htmlFor="area-search">Search anywhere in the United States</label><div><input id="area-search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="City, state, or ZIP code" autoComplete="off"/><button type="submit" disabled={state==="loading"}>Search</button><button type="button" className="refresh-button" onClick={()=>void load(data.scope==="local"?data.query:"")} disabled={state==="loading"}>↻</button></div>{suggestions.length>0&&<div className="suggestion-menu">{suggestions.map(place=><button type="button" key={`${place.label}-${place.latitude}`} onClick={()=>pick(place)}><span>⌖</span>{place.label}</button>)}</div>}{isLocal&&<button className="usa-reset" type="button" onClick={()=>{setQuery("");setSuggestions([]);void load()}}>Return to USA overview</button>}{searchError&&<p className="search-error" role="alert">{searchError}</p>}</form><a className="photo-credit" href={image.page} target="_blank" rel="noreferrer">Artwork: {image.credit} ↗</a><div className="slide-dots" aria-label="Rotating backgrounds">{backgrounds.map((_,index)=><button key={index} onClick={()=>setBackground(index)} className={index===background?"selected":""} aria-label={`Show background ${index+1}`}/>)}</div></section>
  <section className="dashboard" id="overview"><div className="area-heading"><div><p className="eyebrow">{isLocal?"Selected area":"National overview"}</p><h2>{data.location}</h2></div><p>{date}<br/><span>{data.generatedAt?`Feed checked ${relative(data.generatedAt)}`:"Waiting for official feeds"}</span></p></div>
   {state==="error"&&<div className="feed-notice" role="alert">Sentinel could not reach its data service. Try refreshing in a moment.</div>}
   <div className={`summary-grid ${isLocal?"with-mini-map":""}`}><article className="overall-card"><div className={`risk-gauge ${elevated?"":"normal"}`}><strong>{elevated?data.weather.count:"CLEAR"}</strong><span>{elevated?isLocal?"local alerts":"active U.S. alerts":"No active alerts"}</span></div><div><p className="eyebrow">{isLocal?"Local status":"Nationwide status"}</p><h3>{elevated?isLocal?"Review local advisories":"Active alerts across the U.S.":`No active alerts for ${data.location}`}</h3><p>{data.weather.headline}</p><a href="#updates">See current alert activity →</a></div></article><article className="conditions-card"><p className="eyebrow">{isLocal?"Current conditions":"Official feed summary"}</p><div className="temperature">{isLocal&&data.currentWeather.temperature!==null?data.currentWeather.temperature:data.weather.count}<span>{isLocal?"°F":" alerts"}</span></div><p>{isLocal?`${data.currentWeather.condition} · Feels like ${data.currentWeather.apparent??"—"}°F`:"National Weather Service · United States"}</p><dl><div><dt>{isLocal?"Humidity":"USGS events"}</dt><dd>{isLocal?`${data.currentWeather.humidity??"—"}%`:data.earthquakes.count}</dd></div><div><dt>{isLocal?"Wind":"Strongest"}</dt><dd>{isLocal?`${data.currentWeather.wind??"—"} mph`:data.earthquakes.strongestMagnitude??"—"}</dd></div><div><dt>Window</dt><dd>Past 24 hr</dd></div></dl></article>{isLocal&&data.coordinates&&<MiniLocationMap latitude={data.coordinates.latitude} longitude={data.coordinates.longitude} label={data.location}/>}</div>
   <div className="section-title" id="hazards"><div><p className="eyebrow">Hazard overview</p><h2>{isLocal?`Monitoring ${data.location}`:"Monitoring the United States"}</h2></div><span>{state==="live"?"Live data":"Checking data"}</span></div><div className="hazard-grid">{hazards.map(item=><a className="hazard-card" href={item.href} target="_blank" rel="noreferrer" key={item.name}><span className="hazard-icon">{item.icon}</span><div><h3>{item.name}{item.live&&<small> LIVE</small>}</h3><p>{item.note}</p><b className="card-source">View {item.source} source ↗</b></div><span className={`level ${item.live&&item.level!=="Normal"?"watch":""}`}>{item.level}</span></a>)}</div>
   {isLocal&&<section className="water-panel"><div className="water-head"><div><p className="eyebrow">NOAA National Water Prediction Service</p><h2>Rivers and gauges near {data.location}</h2></div><a href={intel?.water.sourceUrl??"https://water.noaa.gov/"} target="_blank" rel="noreferrer">Open NOAA water map ↗</a></div>{water?<><div className="water-primary"><div><span>Nearest gauge · {water.distanceMiles} mi</span><h3>{water.name}</h3><p>{water.impact??"No nearby flood-impact statement is active at the current river stage."}</p></div><dl><div><dt>River level</dt><dd>{water.stage??"—"} {water.stageUnit}</dd></div><div><dt>Streamflow</dt><dd>{water.streamflow??"—"} {water.streamflowUnit}</dd></div><div><dt>Flood category</dt><dd>{water.category}</dd></div><div><dt>Forecast</dt><dd>{water.forecastStage??water.forecastCategory}</dd></div></dl></div><div className="gauge-strip">{intel?.water.gauges.map(g=><a key={g.id} href={g.url} target="_blank" rel="noreferrer"><strong>{g.name}</strong><span>{g.distanceMiles} mi · {g.stage??"—"} {g.unit??""}</span><b>{g.category} ↗</b></a>)}</div></>:<p className="empty-state">{intel?"No NOAA NWPS gauges were found within the nearby search area.":"Checking nearby river gauges…"}</p>}</section>}
   <section className="expanded-sources"><div className="section-title"><div><p className="eyebrow">Expanded official intelligence</p><h2>More ways to understand the risk</h2></div></div><div className="intel-grid"><article className="intel-card"><span>FEMA OpenFEMA</span><strong>{intel?.fema.available?`${intel.fema.count} recent declarations`:"Checking declarations"}</strong><p>Official federal disaster declarations and affected states.</p><div>{intel?.fema.declarations.slice(0,3).map(d=><a href={d.url} target="_blank" rel="noreferrer" key={d.disasterNumber}>{d.state} · {d.incidentType}: {d.declarationTitle} ↗</a>)}</div></article><article className="intel-card"><span>NOAA National Hurricane Center</span><strong>{intel?.hurricanes.available?`${intel.hurricanes.count} active systems`:"Checking active systems"}</strong><p>Official tropical cyclone positions, wind intensity, and advisories.</p><div>{intel?.hurricanes.storms.slice(0,3).map(s=><a href={s.url} target="_blank" rel="noreferrer" key={s.name}>{s.classification} {s.name} · {s.windMph} mph ↗</a>)}</div></article><article className="intel-card connector-card"><span>EPA AirNow</span><strong>{intel?.connectors.airnow.configured?"Connected":"Secure key required"}</strong><p>AQI, smoke, particulate conditions, health categories, and forecasts.</p><a href="https://docs.airnowapi.org/account/request/" target="_blank" rel="noreferrer">Get a free AirNow key ↗</a></article><article className="intel-card connector-card"><span>NASA FIRMS</span><strong>{intel?.connectors.firms.configured?"Connected":"Secure MAP key required"}</strong><p>Near-real-time satellite fire detections and map hotspots.</p><a href="https://firms.modaps.eosdis.nasa.gov/api/area/" target="_blank" rel="noreferrer">Get a free FIRMS key ↗</a></article></div><div className="specialized-strip">{intel?.specialized.map(source=><a href={source.url} target="_blank" rel="noreferrer" key={source.name}><strong>{source.name}</strong><span>{source.agency} ↗</span></a>)}</div></section>
   <section className="updates" id="updates"><div className="section-title"><div><p className="eyebrow">Official activity</p><h2>{isLocal?"Recent local updates":"Latest alerts across the USA"}</h2></div></div><div className="update-list">{data.updates.length?data.updates.map((item,index)=><a href={item.kind==="weather"?data.sources.nws:data.sources.usgs} target="_blank" rel="noreferrer" key={`${item.title}-${index}`}><time>{relative(item.time)}</time><span className={`update-marker ${item.kind}`}/><div><h3>{item.title} <small>↗</small></h3><p>{item.detail}</p></div></a>):<p className="empty-state">{state==="loading"?"Contacting official feeds…":"No recent feed items are available."}</p>}</div></section>
   <div className="source-panel weather-sources" id="sources"><div><span>Verified public sources</span><strong>Explore the original data</strong></div><a href={data.sources.weather} target="_blank" rel="noreferrer">Open-Meteo <b>↗</b></a><a href={data.sources.nws} target="_blank" rel="noreferrer">NWS <b>↗</b></a><a href={data.sources.usgs} target="_blank" rel="noreferrer">USGS <b>↗</b></a><a href="https://water.noaa.gov/" target="_blank" rel="noreferrer">NOAA Water <b>↗</b></a><a href="https://www.fema.gov/about/openfema" target="_blank" rel="noreferrer">OpenFEMA <b>↗</b></a></div><p className="source-note">Weather data: Open-Meteo (CC BY 4.0) and National Weather Service. River data: NOAA NWPS. Disaster declarations: FEMA OpenFEMA. Tropical cyclone data: NOAA NHC. Sentinel summarizes public feeds and does not issue emergency alerts.</p>
  </section><footer><div><img src="/sentinel-logo.webp" alt="Sentinel logo"/><strong>Sentinel</strong><p>An open-source disaster awareness project.</p></div><p>Informational service — always follow official emergency guidance.</p></footer>
 </main>
}
