"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
type FeedItem={title:string;detail:string;time:string;kind:"weather"|"earthquake"};
type Data={generatedAt:string;scope:"national"|"local";query:string;location:string;geocoded:boolean;availability:{nws:boolean;usgs:boolean;weather:boolean};currentWeather:{available:boolean;temperature:number|null;apparent:number|null;humidity:number|null;wind:number|null;condition:string;icon:string;sourceName:string;sourceUrl:string};weather:{count:number;highest:string;headline:string};earthquakes:{count:number;strongestMagnitude:number|null;headline:string};updates:FeedItem[];sources:{nws:string;usgs:string;weather:string}};
const fallback:Data={generatedAt:"",scope:"national",query:"",location:"United States",geocoded:false,availability:{nws:false,usgs:false,weather:true},currentWeather:{available:true,temperature:null,apparent:null,humidity:null,wind:null,condition:"Nationwide overview",icon:"◎",sourceName:"National Weather Service",sourceUrl:"https://www.weather.gov/"},weather:{count:0,highest:"Loading",headline:"Loading nationwide alerts"},earthquakes:{count:0,strongestMagnitude:null,headline:"Loading earthquake activity"},updates:[],sources:{nws:"https://www.weather.gov/",usgs:"https://earthquake.usgs.gov/",weather:"https://open-meteo.com/"}};
const backgrounds=[
 {url:"https://images.unsplash.com/photo-1616652962924-eb295f81bdf3?auto=format&fit=crop&fm=jpg&q=82&w=2200",credit:"Shane Gallagher",page:"https://unsplash.com/photos/dramatic-storm-clouds-gather-over-a-vast-landscape-sFkEeMLrlnM"},
 {url:"https://images.unsplash.com/photo-1657720976914-acf295711399?auto=format&fit=crop&fm=jpg&q=82&w=2200",credit:"Dave Hoefler",page:"https://unsplash.com/photos/a-field-with-trees-and-clouds-in-the-sky-Zymaf0qJKTg"},
 {url:"https://images.unsplash.com/photo-1504383874894-e9da0c82c078?auto=format&fit=crop&fm=jpg&q=82&w=2200",credit:"Raychel Sanner",page:"https://unsplash.com/photos/a-large-plume-of-smoke-billows-into-the-sky-in8Xbu031c0"}
];
function relative(value:string){const minutes=Math.max(0,Math.round((Date.now()-new Date(value).getTime())/60000));return minutes<1?"Just now":minutes<60?`${minutes} min ago`:`${Math.floor(minutes/60)} hr ago`}

export default function Home(){
 const[data,setData]=useState(fallback),[state,setState]=useState<"loading"|"live"|"error">("loading"),[query,setQuery]=useState(""),[background,setBackground]=useState(0),[searchError,setSearchError]=useState("");
 const date=useMemo(()=>new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric"}).format(new Date()),[]);
 const load=useCallback(async(value="")=>{setState("loading");setSearchError("");try{const response=await fetch(`/api/hazards${value?`?q=${encodeURIComponent(value)}`:""}`,{cache:"no-store"});if(!response.ok)throw new Error();const next=await response.json() as Data;if(value&&!next.geocoded){setSearchError("Location not found. Try a city and state or a five-digit ZIP code.");setState("live");return}setData(next);setState("live")}catch{setState("error")}},[]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{const timer=setInterval(()=>setBackground(value=>(value+1)%backgrounds.length),12000);return()=>clearInterval(timer)},[]);
 function search(event:FormEvent){event.preventDefault();if(query.trim())void load(query.trim())}
 const image=backgrounds[background],feedCount=Object.values(data.availability).filter(Boolean).length,partial=state==="live"&&feedCount<3,elevated=data.weather.count>0,isLocal=data.scope==="local";
 const hazards=[{name:isLocal?"Local weather alerts":"U.S. weather alerts",level:data.weather.count?data.weather.highest:data.availability.nws?"Normal":"Offline",note:data.weather.headline,icon:"ϟ",live:data.availability.nws,href:data.sources.nws,source:"NWS"},{name:isLocal?"Nearby earthquakes":"Earthquakes",level:data.earthquakes.count?`${data.earthquakes.count} today`:data.availability.usgs?"Normal":"Offline",note:data.earthquakes.headline,icon:"⌁",live:data.availability.usgs,href:data.sources.usgs,source:"USGS"},{name:"Flood monitoring",level:"Source",note:"Explore real-time water conditions",icon:"≈",live:false,href:"https://waterdata.usgs.gov/nwis",source:"USGS Water"},{name:"Wildfire activity",level:"Source",note:"Explore NASA satellite fire detections",icon:"△",live:false,href:"https://firms.modaps.eosdis.nasa.gov/",source:"NASA FIRMS"}];
 return <main>
  <header className="topbar"><a className="brand" href="#top"><img src="/sentinel-logo.svg" alt=""/><span>Sentinel</span></a><nav aria-label="Primary navigation"><a className="active" href="#overview">Overview</a><a href="#hazards">Hazards</a><a href="#updates">Updates</a><a href="#sources">Sources</a></nav><div className="header-tools"><a className="local-weather" href={data.currentWeather.sourceUrl} target="_blank" rel="noreferrer"><span>{data.currentWeather.icon}</span><div><strong>{isLocal&&data.currentWeather.temperature!==null?`${data.currentWeather.temperature}°F`:"USA"}</strong><small>{isLocal?`${data.currentWeather.condition} · ${data.location}`:"Nationwide alert overview"}</small></div></a><span className={`status-dot ${partial?"loading":state}`}><i/>{partial?`${feedCount}/3 feeds`:state==="live"?"Live":"Updating"}</span></div></header>
  <section className="hero nationwide-hero" id="top" style={{backgroundImage:`linear-gradient(105deg,rgba(5,40,30,.93),rgba(13,67,48,.62)),url(${image.url})`}}><div><p className="eyebrow">United States hazard monitor</p><h1>{isLocal?data.location:"One country. One clear view."}</h1><p className="lede">{isLocal?"Localized alerts, weather, and nearby earthquake activity from official public sources.":"Active alerts across the United States, with local details available by city, state, or ZIP code."}</p></div><form className="location-form search-form" onSubmit={search}><label htmlFor="area-search">Search anywhere in the United States</label><div><input id="area-search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="City, state, or ZIP code"/><button type="submit" disabled={state==="loading"}>Search</button><button type="button" className="refresh-button" onClick={()=>void load(data.scope==="local"?data.query:"")} disabled={state==="loading"}>↻</button></div>{isLocal&&<button className="usa-reset" type="button" onClick={()=>{setQuery("");void load()}}>Return to USA overview</button>}{searchError&&<p className="search-error" role="alert">{searchError}</p>}</form><a className="photo-credit" href={image.page} target="_blank" rel="noreferrer">Background: {image.credit} / Unsplash ↗</a><div className="slide-dots" aria-label="Rotating backgrounds">{backgrounds.map((_,index)=><button key={index} onClick={()=>setBackground(index)} className={index===background?"selected":""} aria-label={`Show background ${index+1}`}/>)}</div></section>
  <section className="dashboard" id="overview"><div className="area-heading"><div><p className="eyebrow">{isLocal?"Selected area":"National overview"}</p><h2>{data.location}</h2></div><p>{date}<br/><span>{data.generatedAt?`Feed checked ${relative(data.generatedAt)}`:"Waiting for official feeds"}</span></p></div>
   {state==="error"&&<div className="feed-notice" role="alert">Sentinel could not reach its data service. Try refreshing in a moment.</div>}
   <div className="summary-grid"><article className="overall-card"><div className={`risk-gauge ${elevated?"":"normal"}`}><strong>{elevated?data.weather.count:"CLEAR"}</strong><span>{elevated?isLocal?"local alerts":"active U.S. alerts":"No active alerts"}</span></div><div><p className="eyebrow">{isLocal?"Local status":"Nationwide status"}</p><h3>{elevated?isLocal?"Review local advisories":"Active alerts across the U.S.":`No active alerts for ${data.location}`}</h3><p>{data.weather.headline}</p><a href="#updates">See current alert activity →</a></div></article><article className="conditions-card"><p className="eyebrow">{isLocal?"Current conditions":"Official feed summary"}</p><div className="temperature">{isLocal&&data.currentWeather.temperature!==null?data.currentWeather.temperature:data.weather.count}<span>{isLocal?"°F":" alerts"}</span></div><p>{isLocal?`${data.currentWeather.condition} · Feels like ${data.currentWeather.apparent??"—"}°F`:"National Weather Service · United States"}</p><dl><div><dt>{isLocal?"Humidity":"USGS events"}</dt><dd>{isLocal?`${data.currentWeather.humidity??"—"}%`:data.earthquakes.count}</dd></div><div><dt>{isLocal?"Wind":"Strongest"}</dt><dd>{isLocal?`${data.currentWeather.wind??"—"} mph`:data.earthquakes.strongestMagnitude??"—"}</dd></div><div><dt>Window</dt><dd>Past 24 hr</dd></div></dl></article></div>
   <div className="section-title" id="hazards"><div><p className="eyebrow">Hazard overview</p><h2>{isLocal?`Monitoring ${data.location}`:"Monitoring the United States"}</h2></div><span>{state==="live"?"Live data":"Checking data"}</span></div><div className="hazard-grid">{hazards.map(item=><a className="hazard-card" href={item.href} target="_blank" rel="noreferrer" key={item.name}><span className="hazard-icon">{item.icon}</span><div><h3>{item.name}{item.live&&<small> LIVE</small>}</h3><p>{item.note}</p><b className="card-source">View {item.source} source ↗</b></div><span className={`level ${item.live&&item.level!=="Normal"?"watch":""}`}>{item.level}</span></a>)}</div>
   <section className="updates" id="updates"><div className="section-title"><div><p className="eyebrow">Official activity</p><h2>{isLocal?"Recent local updates":"Latest alerts across the USA"}</h2></div></div><div className="update-list">{data.updates.length?data.updates.map((item,index)=><a href={item.kind==="weather"?data.sources.nws:data.sources.usgs} target="_blank" rel="noreferrer" key={`${item.title}-${index}`}><time>{relative(item.time)}</time><span className={`update-marker ${item.kind}`}/><div><h3>{item.title} <small>↗</small></h3><p>{item.detail}</p></div></a>):<p className="empty-state">{state==="loading"?"Contacting official feeds…":"No recent feed items are available."}</p>}</div></section>
   <div className="source-panel weather-sources" id="sources"><div><span>Verified public sources</span><strong>Explore the original data</strong></div><a href={data.sources.weather} target="_blank" rel="noreferrer">Open-Meteo Weather <b>↗</b></a><a href={data.sources.nws} target="_blank" rel="noreferrer">National Weather Service <b>↗</b></a><a href={data.sources.usgs} target="_blank" rel="noreferrer">USGS Earthquakes <b>↗</b></a></div><p className="source-note">Weather data: Open-Meteo (CC BY 4.0) and National Weather Service. Background photographs: Shane Gallagher, Dave Hoefler, and Raychel Sanner on Unsplash. Sentinel summarizes public feeds and does not issue emergency alerts.</p>
  </section><footer><div><img src="/sentinel-logo.svg" alt="Sentinel logo"/><strong>Sentinel</strong><p>An open-source disaster awareness project.</p></div><p>Informational service — always follow official emergency guidance.</p></footer>
 </main>
}
