type GaugeStatus={primary?:number;primaryUnit?:string;secondary?:number;secondaryUnit?:string;floodCategory?:string;validTime?:string};
type Gauge={lid:string;name:string;latitude:number;longitude:number;status?:{observed?:GaugeStatus;forecast?:GaugeStatus}};
type GaugeList={gauges?:Gauge[]};
type GaugeDetail=Gauge&{flood?:{categories?:Record<string,{stage?:number;flow?:number}>;impacts?:Array<{stage?:number;statement?:string}>}};
type FemaRow={disasterNumber:number;state:string;declarationDate:string;incidentType:string;declarationTitle:string};
type FemaResponse={DisasterDeclarationsSummaries?:FemaRow[]};
type Storm={id:string;name:string;classification:string;intensity:string;latitude:string;longitude:string;lastUpdate:string;publicAdvisory?:{url?:string}};
type StormResponse={activeStorms?:Storm[]};

async function safe<T>(url:string):Promise<T|null>{try{const response=await fetch(url,{headers:{"User-Agent":"SentinelDisasterAlert/0.3 (open-source educational project)",Accept:"application/json"},cache:"no-store"});return response.ok?await response.json() as T:null}catch{return null}}
function miles(a:number,b:number,c:number,d:number){const r=3958.8,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p*Math.cos((a+c)*p/2);return Math.sqrt(x*x+y*y)*r}
function readableCategory(value="unknown"){return value.replace(/^fcst_/,"").replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}
function valid(value?:number){return typeof value==="number"&&value>-900}

export async function GET(request:Request){
 const params=new URL(request.url).searchParams,latitude=Number(params.get("lat")),longitude=Number(params.get("lon")),hasPoint=params.has("lat")&&params.has("lon")&&Number.isFinite(latitude)&&Number.isFinite(longitude);
 const gaugeUrl=hasPoint?`https://api.water.noaa.gov/nwps/v1/gauges?bbox.xmin=${longitude-.7}&bbox.ymin=${latitude-.55}&bbox.xmax=${longitude+.7}&bbox.ymax=${latitude+.55}&srid=EPSG_4326`:"";
 const[gaugeList,fema,storms]=await Promise.all([gaugeUrl?safe<GaugeList>(gaugeUrl):Promise.resolve(null),safe<FemaResponse>("https://www.fema.gov/api/open/v2/DisasterDeclarationsSummaries?$orderby=declarationDate%20desc&$top=60"),safe<StormResponse>("https://www.nhc.noaa.gov/CurrentStorms.json")]);
 const nearby=(gaugeList?.gauges??[]).map(g=>({...g,distance:miles(latitude,longitude,g.latitude,g.longitude)})).sort((a,b)=>a.distance-b.distance).slice(0,5),closest=nearby[0],detail=closest?await safe<GaugeDetail>(`https://api.water.noaa.gov/nwps/v1/gauges/${closest.lid}`):null;
 const seen=new Set<number>(),declarations=(fema?.DisasterDeclarationsSummaries??[]).filter(row=>{if(seen.has(row.disasterNumber))return false;seen.add(row.disasterNumber);return true}).slice(0,6),observed=detail?.status?.observed??closest?.status?.observed,forecast=detail?.status?.forecast??closest?.status?.forecast,currentStage=valid(observed?.primary)?observed?.primary:null,impact=detail?.flood?.impacts?.filter(i=>valid(i.stage)&&i.statement).sort((a,b)=>(a.stage??0)-(b.stage??0)).find(i=>(i.stage??0)>=(currentStage??0));
 return Response.json({generatedAt:new Date().toISOString(),water:{available:hasPoint&&gaugeList!==null,nearbyCount:nearby.length,closest:closest?{id:closest.lid,name:closest.name,distanceMiles:Number(closest.distance.toFixed(1)),stage:currentStage,stageUnit:observed?.primaryUnit||null,streamflow:valid(observed?.secondary)?observed?.secondary:null,streamflowUnit:observed?.secondaryUnit||null,category:readableCategory(observed?.floodCategory),forecastStage:valid(forecast?.primary)?forecast?.primary:null,forecastCategory:readableCategory(forecast?.floodCategory),updatedAt:observed?.validTime||null,impact:impact?.statement||null,url:`https://water.noaa.gov/gauges/${closest.lid.toLowerCase()}`}:null,gauges:nearby.map(g=>({id:g.lid,name:g.name,distanceMiles:Number(g.distance.toFixed(1)),category:readableCategory(g.status?.observed?.floodCategory),stage:valid(g.status?.observed?.primary)?g.status?.observed?.primary:null,unit:g.status?.observed?.primaryUnit||null,url:`https://water.noaa.gov/gauges/${g.lid.toLowerCase()}`})),sourceUrl:"https://water.noaa.gov/"},fema:{available:fema!==null,count:declarations.length,declarations:declarations.map(row=>({...row,url:`https://www.fema.gov/disaster/${row.disasterNumber}`})),sourceUrl:"https://www.fema.gov/disaster/declarations"},hurricanes:{available:storms!==null,count:storms?.activeStorms?.length??0,storms:(storms?.activeStorms??[]).slice(0,4).map(s=>({name:s.name,classification:s.classification,windMph:Number(s.intensity),position:`${s.latitude}, ${s.longitude}`,updatedAt:s.lastUpdate,url:s.publicAdvisory?.url??"https://www.nhc.noaa.gov/"})),sourceUrl:"https://www.nhc.noaa.gov/"},connectors:{airnow:{configured:Boolean(process.env.AIRNOW_API_KEY),url:"https://www.airnow.gov/"},firms:{configured:Boolean(process.env.FIRMS_MAP_KEY),url:"https://firms.modaps.eosdis.nasa.gov/"}},specialized:[{name:"Severe-storm outlooks",agency:"NOAA Storm Prediction Center",url:"https://www.spc.noaa.gov/products/outlook/"},{name:"Tsunami warnings",agency:"NOAA U.S. Tsunami Warning System",url:"https://www.tsunami.gov/"},{name:"Coastal flooding & tides",agency:"NOAA Tides and Currents",url:"https://tidesandcurrents.noaa.gov/"}]},{headers:{"Cache-Control":"public, max-age=120, s-maxage=300"}})
}
