"use client";
import {useEffect,useRef,useState} from "react";
import maplibregl,{Map as MapLibreMap,Marker} from "maplibre-gl";
type Suggestion={label:string;latitude:number;longitude:number};
export default function MapPage(){
 const container=useRef<HTMLDivElement>(null),map=useRef<MapLibreMap|null>(null),marker=useRef<Marker|null>(null);const[query,setQuery]=useState(""),[suggestions,setSuggestions]=useState<Suggestion[]>([]),[selected,setSelected]=useState<Suggestion|null>(null),[loading,setLoading]=useState(false);
 useEffect(()=>{if(!container.current||map.current)return;const instance=new maplibregl.Map({container:container.current,center:[-98.5795,39.8283],zoom:3.1,style:{version:8,sources:{osm:{type:"raster",tiles:["https://tile.openstreetmap.org/{z}/{x}/{y}.png"],tileSize:256,attribution:"© OpenStreetMap contributors"}},layers:[{id:"osm",type:"raster",source:"osm"}]}});instance.addControl(new maplibregl.NavigationControl(),"top-right");instance.on("click",event=>void choose(event.lngLat.lat,event.lngLat.lng));map.current=instance;return()=>{instance.remove();map.current=null}},[]);
 useEffect(()=>{if(query.trim().length<2){setSuggestions([]);return}const controller=new AbortController(),timer=setTimeout(async()=>{try{const response=await fetch(`/api/suggest?q=${encodeURIComponent(query)}`,{signal:controller.signal});const data=await response.json() as {suggestions:Suggestion[]};setSuggestions(data.suggestions)}catch{}},250);return()=>{clearTimeout(timer);controller.abort()}},[query]);
 async function choose(latitude:number,longitude:number,label?:string){setLoading(true);marker.current?.remove();marker.current=new maplibregl.Marker({color:"#e9593f"}).setLngLat([longitude,latitude]).addTo(map.current!);map.current?.flyTo({center:[longitude,latitude],zoom:label?8:6});try{if(label)setSelected({label,latitude,longitude});else{const response=await fetch(`/api/location?lat=${latitude}&lon=${longitude}`);setSelected(await response.json() as Suggestion)}}finally{setLoading(false)}}
 function pick(place:Suggestion){setQuery(place.label);setSuggestions([]);void choose(place.latitude,place.longitude,place.label)}
 return <main className="map-page"><header className="topbar"><a className="brand" href="/"><img src="/sentinel-logo.svg" alt=""/><span>Sentinel</span></a><nav aria-label="Primary navigation"><a href="/">Overview</a><a href="/#hazards">Hazards</a><a href="/#updates">Updates</a><a href="/#sources">Sources</a><a className="active" href="/map">Map</a></nav><a className="map-back" href="/">Back to dashboard</a></header><section className="map-intro"><div><p className="eyebrow">Explore the United States</p><h1>Choose a place on the map</h1><p>Search for a city or drop a pin anywhere in the U.S. to open its local weather and hazard dashboard.</p></div><div className="map-search"><label htmlFor="map-place">Find a U.S. location</label><input id="map-place" value={query} onChange={event=>setQuery(event.target.value)} placeholder="City, state, or ZIP code" autoComplete="off"/>{suggestions.length>0&&<div className="suggestion-menu">{suggestions.map(place=><button key={`${place.label}-${place.latitude}`} onClick={()=>pick(place)}><span>⌖</span>{place.label}</button>)}</div>}</div></section><section className="map-shell"><div className="map-canvas" ref={container}/><aside className="map-selection"><span className="pin-symbol">⌖</span><p className="eyebrow">Selected location</p><h2>{loading?"Finding nearest city…":selected?.label??"Drop a pin to begin"}</h2><p>{selected?"Your pin is ready. Open Sentinel to see the latest available alerts, weather, and earthquake activity for this area.":"Click anywhere on the map. We’ll identify the nearest city using National Weather Service location data."}</p>{selected&&<a href={`/?q=${encodeURIComponent(selected.label)}`}>Open {selected.label} in Sentinel →</a>}</aside></section><p className="map-credit">Map data © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap contributors</a>. Location lookup provided by the National Weather Service.</p></main>
}
