type NwsAlert={properties:{event?:string;headline?:string;severity?:string;sent?:string;areaDesc?:string}};
type Quake={properties:{mag?:number;place?:string;time?:number;title?:string}};
type Meteo={current?:{temperature_2m?:number;apparent_temperature?:number;relative_humidity_2m?:number;wind_speed_10m?:number;weather_code?:number}};
type Observation={properties?:{temperature?:{value?:number};relativeHumidity?:{value?:number};windSpeed?:{value?:number};textDescription?:string}};
type OpenGeo={results?:Array<{name:string;admin1?:string;latitude:number;longitude:number}>};
type CensusGeo={result?:{addressMatches?:Array<{coordinates?:{x:number;y:number};matchedAddress?:string}>}};
type NwsPoints={properties?:{observationStations?:string}};type StationList={features?:Array<{id?:string}>};

const ranks:Record<string,number>={Extreme:4,Severe:3,Moderate:2,Minor:1,Unknown:0};
function label(code=0){if(code===0)return{condition:"Clear",icon:"☀"};if(code<=3)return{condition:"Partly cloudy",icon:"◐"};if(code<=48)return{condition:"Foggy",icon:"≋"};if(code<=67)return{condition:"Rain",icon:"☂"};if(code<=77)return{condition:"Snow",icon:"✳"};if(code<=82)return{condition:"Rain showers",icon:"☂"};if(code<=86)return{condition:"Snow showers",icon:"✳"};return{condition:"Thunderstorms",icon:"ϟ"}}
function iconFor(text=""){const v=text.toLowerCase();if(v.includes("thunder"))return"ϟ";if(v.includes("rain")||v.includes("shower"))return"☂";if(v.includes("snow"))return"✳";if(v.includes("fog")||v.includes("mist"))return"≋";if(v.includes("cloud"))return"◐";return"☀"}
async function safe<T>(url:string,headers?:HeadersInit):Promise<T|null>{try{const response=await fetch(url,{headers,cache:"no-store"});return response.ok?await response.json() as T:null}catch{return null}}
async function geocode(query:string){
 const encoded=encodeURIComponent(query);
 const[open,census]=await Promise.all([safe<OpenGeo>(`https://geocoding-api.open-meteo.com/v1/search?name=${encoded}&count=1&language=en&countryCode=US`),safe<CensusGeo>(`https://geocoding.geo.census.gov/geocoder/locations/onelineaddress?address=${encoded}&benchmark=Public_AR_Current&format=json`)]);
 const first=open?.results?.[0];if(first)return{latitude:first.latitude,longitude:first.longitude,label:[first.name,first.admin1].filter(Boolean).join(", ")};
 const match=census?.result?.addressMatches?.[0];if(match?.coordinates)return{latitude:match.coordinates.y,longitude:match.coordinates.x,label:match.matchedAddress??query};return null
}
async function currentWeather(latitude:number,longitude:number,agent:HeadersInit){
 const meteo=await safe<Meteo>(`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m,apparent_temperature,relative_humidity_2m,wind_speed_10m,weather_code&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=auto`);
 if(meteo?.current){const c=meteo.current;return{available:true,temperature:Math.round(c.temperature_2m??0),apparent:Math.round(c.apparent_temperature??0),humidity:Math.round(c.relative_humidity_2m??0),wind:Math.round(c.wind_speed_10m??0),...label(c.weather_code),sourceName:"Open-Meteo",sourceUrl:"https://open-meteo.com/"}}
 const points=await safe<NwsPoints>(`https://api.weather.gov/points/${latitude.toFixed(4)},${longitude.toFixed(4)}`,agent),stations=points?.properties?.observationStations?await safe<StationList>(points.properties.observationStations,agent):null,station=stations?.features?.[0]?.id,observation=station?await safe<Observation>(`${station}/observations/latest`,agent):null,p=observation?.properties;
 if(p?.temperature?.value!=null)return{available:true,temperature:Math.round(p.temperature.value*9/5+32),apparent:Math.round(p.temperature.value*9/5+32),humidity:Math.round(p.relativeHumidity?.value??0),wind:Math.round((p.windSpeed?.value??0)*0.621371),condition:p.textDescription??"Current conditions",icon:iconFor(p.textDescription),sourceName:"National Weather Service",sourceUrl:station??"https://www.weather.gov/"};
 return{available:false,temperature:null,apparent:null,humidity:null,wind:null,condition:"Weather unavailable",icon:"◌",sourceName:"Weather source",sourceUrl:"https://www.weather.gov/"}
}

export async function GET(request:Request){
 const query=new URL(request.url).searchParams.get("q")?.trim()??"",place=query?await geocode(query):null,scope=place?"local":"national",location=place?.label??"United States";
 const agent={"User-Agent":"SentinelDisasterAlert/0.2 (open-source educational project)",Accept:"application/geo+json, application/json"};
 const alertUrl=place?`https://api.weather.gov/alerts/active?point=${place.latitude},${place.longitude}`:"https://api.weather.gov/alerts/active";
 const quakeUrl=place?`https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&starttime=${new Date(Date.now()-86400000).toISOString()}&latitude=${place.latitude}&longitude=${place.longitude}&maxradiuskm=500&orderby=time`:`https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson`;
 const[alertsJson,quakesJson,weather]=await Promise.all([safe<{features?:NwsAlert[]}>(alertUrl,agent),safe<{features?:Quake[]}>(quakeUrl),place?currentWeather(place.latitude,place.longitude,agent):Promise.resolve({available:true,temperature:null,apparent:null,humidity:null,wind:null,condition:"Nationwide overview",icon:"◎",sourceName:"National Weather Service",sourceUrl:"https://www.weather.gov/"})]);
 const alerts=alertsJson?.features??[],quakes=quakesJson?.features??[],availability={nws:alertsJson!==null,usgs:quakesJson!==null,weather:weather.available},highest=alerts.reduce((best,x)=>ranks[x.properties.severity??"Unknown"]>ranks[best]?x.properties.severity??"Unknown":best,"Unknown"),strongest=quakes.reduce((best,x)=>Math.max(best,x.properties.mag??0),0);
 const alertUpdates=alerts.slice(0,8).map(x=>({title:x.properties.event??"Weather alert",detail:x.properties.areaDesc??x.properties.headline??location,time:x.properties.sent??new Date().toISOString(),kind:"weather" as const})),quakeUpdates=quakes.slice(0,4).map(x=>({title:x.properties.title??`M${x.properties.mag??"?"} earthquake`,detail:x.properties.place??"Location unavailable",time:new Date(x.properties.time??Date.now()).toISOString(),kind:"earthquake" as const}));
 return Response.json({generatedAt:new Date().toISOString(),scope,query,location,geocoded:Boolean(place),coordinates:place?{latitude:place.latitude,longitude:place.longitude}:null,availability,currentWeather:weather,weather:{count:alerts.length,highest:!availability.nws?"Unavailable":alerts.length?highest:"Normal",headline:!availability.nws?"National Weather Service alerts are temporarily unavailable":alerts[0]?.properties.headline??`No active alerts for ${location}`},earthquakes:{count:quakes.length,strongestMagnitude:quakes.length?Number(strongest.toFixed(1)):null,headline:!availability.usgs?"USGS earthquake feed is temporarily unavailable":quakes.length?`${quakes.length} earthquakes recorded in the past 24 hours`:"No earthquakes listed in the past 24 hours"},updates:[...alertUpdates,...quakeUpdates].sort((a,b)=>Date.parse(b.time)-Date.parse(a.time)).slice(0,10),sources:{nws:"https://www.weather.gov/",usgs:"https://earthquake.usgs.gov/",weather:"https://open-meteo.com/"}},{headers:{"Cache-Control":"public, max-age=60, s-maxage=120"}})
}
