type NwsFeature={properties:{event?:string;headline?:string;severity?:string;sent?:string;areaDesc?:string}};type QuakeFeature={properties:{mag?:number;place?:string;time?:number;title?:string}};type Meteo={current?:{temperature_2m?:number;apparent_temperature?:number;relative_humidity_2m?:number;wind_speed_10m?:number;weather_code?:number}};
const ranks:Record<string,number>={Extreme:4,Severe:3,Moderate:2,Minor:1,Unknown:0};
function weatherLabel(code=0){if(code===0)return{condition:"Clear",icon:"☀"};if(code<=3)return{condition:"Partly cloudy",icon:"◐"};if(code<=48)return{condition:"Foggy",icon:"≋"};if(code<=67)return{condition:"Rain",icon:"☂"};if(code<=77)return{condition:"Snow",icon:"✳"};if(code<=82)return{condition:"Rain showers",icon:"☂"};if(code<=86)return{condition:"Snow showers",icon:"✳"};return{condition:"Thunderstorms",icon:"ϟ"}}
async function safeJson<T>(url:string,headers?:HeadersInit):Promise<T|null>{try{const response=await fetch(url,{headers,cache:"no-store"});if(!response.ok)return null;return await response.json() as T}catch{return null}}
export async function GET(){
 const agent={"User-Agent":"SentinelDisasterAlert/0.1 (open-source educational project)",Accept:"application/geo+json, application/json"};
 const[weatherJson,quakeJson,meteoJson]=await Promise.all([
  safeJson<{features?:NwsFeature[]}>("https://api.weather.gov/alerts/active?area=IL",agent),
  safeJson<{features?:QuakeFeature[]}>("https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson"),
  safeJson<Meteo>("https://api.open-meteo.com/v1/forecast?latitude=42.2586&longitude=-87.8406&current=temperature_2m,apparent_temperature,relative_humidity_2m,wind_speed_10m,weather_code&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=America%2FChicago")
 ]);
 const weather=weatherJson?.features??[],quakes=quakeJson?.features??[],current=meteoJson?.current,label=weatherLabel(current?.weather_code),availability={nws:weatherJson!==null,usgs:quakeJson!==null,weather:meteoJson!==null};
 const highest=weather.reduce((best,x)=>ranks[x.properties.severity??"Unknown"]>ranks[best]?x.properties.severity??"Unknown":best,"Unknown"),strongest=quakes.reduce((best,x)=>Math.max(best,x.properties.mag??0),0);
 const wu=weather.slice(0,3).map(x=>({title:x.properties.event??"Weather alert",detail:x.properties.areaDesc??x.properties.headline??"Illinois",time:x.properties.sent??new Date().toISOString(),kind:"weather" as const})),qu=quakes.slice(0,3).map(x=>({title:x.properties.title??`M${x.properties.mag??"?"} earthquake`,detail:x.properties.place??"Location unavailable",time:new Date(x.properties.time??Date.now()).toISOString(),kind:"earthquake" as const}));
 return Response.json({generatedAt:new Date().toISOString(),availability,currentWeather:{available:availability.weather,temperature:current?Math.round(current.temperature_2m??0):null,apparent:current?Math.round(current.apparent_temperature??0):null,humidity:current?Math.round(current.relative_humidity_2m??0):null,wind:current?Math.round(current.wind_speed_10m??0):null,condition:current?label.condition:"Weather unavailable",icon:current?label.icon:"◌"},weather:{count:weather.length,highest:!availability.nws?"Unavailable":weather.length?highest:"Normal",headline:!availability.nws?"National Weather Service feed is temporarily unavailable":weather[0]?.properties.headline??"No active Illinois alerts"},earthquakes:{count:quakes.length,strongestMagnitude:quakes.length?Number(strongest.toFixed(1)):null,headline:!availability.usgs?"USGS earthquake feed is temporarily unavailable":quakes.length?`${quakes.length} earthquakes recorded globally in the past 24 hours`:"No earthquakes listed in the past 24 hours"},updates:[...wu,...qu].sort((a,b)=>Date.parse(b.time)-Date.parse(a.time)).slice(0,6),sources:{nws:"https://www.weather.gov/",usgs:"https://earthquake.usgs.gov/",weather:"https://open-meteo.com/"}},{headers:{"Cache-Control":"public, max-age=60, s-maxage=120"}})
}
